### PR TITLE
URL should be required

### PR DESCRIPTION
**Pull request by penne12**
A URL to the author's website should be required.

### CODE REVIEW

**Comment by jakimfett** [comment]
There are some cases where a URL isn't possible, eg inside a launcher for a pack.

**Comment by penne12** [comment]
@jakimfett Then in the pack's longer description (if in the pack), or the pack's website (if they have one).

**Comment by penne12** [comment]
Or in a text file that the pack makes.

**Comment by jakimfett** [comment]
I'm open to adding wording to the "modpacks" section that says modpacks must provide mod author credit as required by the method of distribution (eg, the launcher), but there are cases where a requirement to compile a list of websites for all the mods just doesn't make sense (eg, a zip file for manual installation).

Yes, it makes sense for the big modpacks, or the ones that get played a lot. But most of the launchers already require a specific form of author credit. 

The purpose of this is to make it easy for players, easy for modpack creators, easy for the mod author, and hard for scammers or thieves. I'm not sure requiring a link does much towards that. 

That said, If you can come up with a non-intrusive way to work in a requirement for a link, I'm willing to consider it.

**Comment by cuchaz** [comment]
I still haven't had time to go over the license again, but I wanted to address this particular issue when I did. My PR a while back had some verbiage to require author attribution on the download page (or other "call to acquire the mod"). It seems that putting a big list of author credits on the download website for a modpack next to the download button is a good way to handle this.

**Pull request closed without merging**
